apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-pg
  template:
    metadata:
      labels:
        app: quarkus-pg
    spec:
      containers:
        - name: quarkus-pg
          image: tiempor3al/quarkus-pg:25d27c28e0227d16e854029af11fc2255edfe7ac
          env:
            - name: POSTGRES_DB
              value: postgres_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-pg-service
spec:
  type: NodePort
  selector:
    app: quarkus-pg
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus-pg-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - quarkus-pg.enjambre.work
      secretName: quarkus-pg-enjambre-workp-tls
  rules:
    - host: quarkus-pg.enjambre.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quarkus-pg-service
                port:
                  number: 8001
